ft: deploy with CA certs
scality/azure-templates pull request #3
Opened 2017-12-19 01:38 UTC by JianqinWang

2017-12-21 19:47 UTC, LaurenSpiegel requested changes

2017-12-21 19:47 UTC, LaurenSpiegel commented on enterprise/startup-script/run.sh
> -sudo nohup docker run -d --name scalityconnect -p 8000:8000 \
why removed?

2017-12-21 19:47 UTC, LaurenSpiegel commented on enterprise/startup-script/run.sh
> ---restart always scality/connect &
why removed?

2017-12-21 19:47 UTC, LaurenSpiegel commented on enterprise/README.md
> -Update the values in `azuredeploy.template.json` to your deployment values, then
don't you mean the parameters json file (connectdeploy.sample.parameters.json) here?  Shouldn't we be git ignoring the correct one? Is that the correct rename?  seems we should be replacing a paramaters.json file.

2017-12-21 19:47 UTC, LaurenSpiegel commented on enterprise/README.md
> +The script automatically replace any dummy values in `azuredeploy.template.json`
replaces

2017-12-21 19:47 UTC, LaurenSpiegel commented on enterprise/README.md
> +The script automatically replace any dummy values in `azuredeploy.template.json`
shouldn't it replace the values in the paramaters.json?

2017-12-21 19:47 UTC, LaurenSpiegel commented on enterprise/README.md
> +Note: Use the same location for all your resources - VHD image, Key Vault, and
by location do you mean region or resource group?

2017-12-21 19:47 UTC, LaurenSpiegel commented on enterprise/README.md
> +Update the remaining values in `azuredeploy.template.json` to your deployment
parameters?

2017-12-21 19:47 UTC, LaurenSpiegel commented on enterprise/README.md
> +[![](http://azuredeploy.net/deploybutton.png)](https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FScality%2Fazure-templates%2Fssl-cert%2Fenterprise%2Faz
why in your slide deck does the button say purchase?

2017-12-21 19:47 UTC, LaurenSpiegel commented on enterprise/azuredeploy.json
> -      "computeApiVersion": "2017-03-30",
why removed?

2017-12-21 19:47 UTC, LaurenSpiegel commented on enterprise/README.md
> +Run the `keyvault.sh` to upload your private key and corresponding .crt file to
We should say at the beginning, before you start you should have ... and list domain set up, the certificates from an authority, etc.

2017-12-21 19:47 UTC, LaurenSpiegel commented on enterprise/azuredeploy.json
> +      "vaultResourceGroup": {
As discussed, let's put the old parameters file, the old run.sh and the old azuredeploy.json in s separate directory called withoutTLS so people can use that if they want.

2017-12-21 19:47 UTC, LaurenSpiegel commented on enterprise/configuration-files/default.template.conf
> +server {
can we put nginx somewhere in the name of this file?  it is confusing because we have the arm conf's as well.

2017-12-21 19:47 UTC, LaurenSpiegel commented on enterprise/configuration-files/nginx.conf.template
> +    server {
why do we need the separate file above if the server configuration is in here as well?

2017-12-21 19:47 UTC, LaurenSpiegel commented on enterprise/deploy.sh
> +#!/bin/bash
remove

2017-12-21 19:47 UTC, LaurenSpiegel commented on enterprise/startup-script/apacheconfiguressl.sh
> +#!/bin/bash
remove

2017-12-21 19:47 UTC, LaurenSpiegel commented on enterprise/startup-script/nginxconfiguressl.sh
> +export STORAGE_ACCESS_ACCOUNT=$1
why are we starting scalityconnect before setting up nginx?

2017-12-21 19:47 UTC, LaurenSpiegel commented on enterprise/startup-script/nginxconfiguressl.sh
> +set -e
might as well -- set -eo pipefail

2017-12-21 19:47 UTC, LaurenSpiegel commented on enterprise/startup-script/nginxconfiguressl.sh
> +until apt-get -y update && apt-get -y install nginx
we should try some finite number of times. 10? and then fail so the person gets an error on deployment.

2017-12-21 19:47 UTC, LaurenSpiegel commented on enterprise/startup-script/nginxconfiguressl.sh
> +fullpath=/var/lib/waagent/$sslcertfilename
this is where the agent just puts it? should we delete from here after moving?

2017-12-21 19:47 UTC, LaurenSpiegel commented on enterprise/configuration-files/nginx.conf.template
> +        server_name ${FQDN};
how does this get populated? if using sed later is this necessary?

2017-12-21 19:47 UTC, LaurenSpiegel commented on enterprise/startup-script/nginxconfiguressl.sh
> +fullpath=/var/lib/waagent/$sslkeyfilename
same as above. get rid of this when done with it?

2017-12-21 19:59 UTC, LaurenSpiegel commented on enterprise/startup-script/nginxconfiguressl.sh
> +until apt-get -y update && apt-get -y install nginx
actually, why don't we have nginx pre-installed on the vm image?

2017-12-21 20:01 UTC, LaurenSpiegel commented on enterprise/startup-script/nginxconfiguressl.sh
> +systemctl restart nginx
what happens if the system is restarted or nginx goes down? docker is taking care of restarting scality connect for us.

2017-12-21 21:23 UTC, JianqinWang commented on enterprise/README.md
> +Note: Use the same location for all your resources - VHD image, Key Vault, and
I meant region - I'll clarify here

2017-12-21 22:25 UTC, JianqinWang commented on enterprise/README.md
> +[![](http://azuredeploy.net/deploybutton.png)](https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FScality%2Fazure-templates%2Fssl-cert%2Fenterprise%2Faz
Are you talking about the final screenshot of the Azure Portal? I think it's to confirm that you want to pay for the VM's that you're running on

2017-12-21 22:49 UTC, JianqinWang commented on enterprise/startup-script/run.sh
> -sudo nohup docker run -d --name scalityconnect -p 8000:8000 \
I removed the nohup, but the line should still be there

2017-12-21 23:47 UTC, LaurenSpiegel commented on enterprise/README.md
> +[![](http://azuredeploy.net/deploybutton.png)](https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FScality%2Fazure-templates%2Fssl-cert%2Fenterprise%2Faz
ok

2018-01-04 19:08 UTC, LaurenSpiegel commented on enterprise/README.md
> +- a valid domain name (you can get one from sites such as [Namecheap](https://www.namecheap.com/) or
get rid of suggestions

2018-01-04 19:09 UTC, LaurenSpiegel commented on enterprise/README.md
> +you can purchase one on sites such as [Digicert](https://www.digicert.com/))
no referrals

2018-01-04 19:19 UTC, LaurenSpiegel commented on withoutSSL/run.sh
> +sudo nohup docker run -d --name scalityconnect -p 8000:8000 \
might as well get rid of nohup here as well

2018-01-04 19:19 UTC, LaurenSpiegel commented on withoutSSL/run.sh
> +--restart always scality/connect &
remove & as well

2018-01-04 19:31 UTC, LaurenSpiegel approved these changes

2018-01-04 20:30 UTC, LaurenSpiegel approved these changes

2018-01-04 20:30 UTC, merged